version: "3.7"
services:
    server:
        image: "server:latest"
        build: 
            context: .
            dockerfile: "Dockerfile"
        depends_on:
            - "redis"
            - postgresql
        ports:
            - "8080:8080"
        volumes:
            - ".:/go/src/github.com/asymptoter/practice-backend"
        container_name: "server"
        restart: always
        command: ["../../scripts/wait-for-it.sh", "postgresql:5432", "--", "go", "run", "main.go"]
    redis:
        image: "redis:alpine"
        ports:
            - "6379:6379"
        container_name: "redis"
    #mysql:
    #    image: "mysql:latest"
    #    command: --default-authentication-plugin=caching_sha2_password
    #    environment:
    #        MYSQL_USER: "asymptoter"
    #        MYSQL_PASSWORD: "password"
    #        MYSQL_ROOT_PASSWORD: "password"
    #        MYSQL_DATABASE: "practice"
    #    ports:
    #        - "3306:3306"
    #    volumes:
    #        - "./databases/mysql/data:/var/lib/mysql"
    #        - "./databases/mysql/init:/docker-entrypoint-initdb.d:ro"
    #    container_name: "mysql"
    postgresql:
        image: postgres:12-alpine
        restart: always
        environment:
            POSTGRES_USER: asymptoter
            POSTGRES_PASSWORD: password
        ports:
            - 5432:5432
        volumes:
            - "./databases/postgres/data:/var/lib/postgresql/"
            - "./databases/postgres/init:/docker-entrypoint-initdb.d/"
        container_name: postgresql
