version: '3'
services:
    server:
        build: 
            context: .
            dockerfile: Dockerfile-server
        depends_on:
            - "mysql"
            - "redis"
        ports:
            - "8080:8080"
        volumes:
            - "./app/server:/go/src/github.com/asymptoter/practice/app/server"
    redis:
        image: "redis:alpine"
        ports:
            - "6379:6379"
    mysql:
        image: "mysql:8.0"
        environment:
            MYSQL_DATABASE: "practice"
            MYSQL_ROOT_PASSWORD: "practice-mysql-password"
            MYSQL_USER: "asymptoter"
            MYSQL_PASSWORD: "password"
        ports:
            - "3306:3306"
        volumes:
            - "./databases/mysql:/var/lib/mysql"
