# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13.1-buster

    working_directory: /Users/ayuang/go/src/github.com/asymptoter/practice-backend
    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Start container and verify it is working
          command: |
            set -x
            docker-compose up -d
