# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: golang:1.13-alpine

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/asymptoter/practice-backend
    steps:
      - checkout

      - run:
          name: Install curl
          command: apk update && apk add curl curl-dev bash
      
      - setup_remote_docker:
          docker_layer_cacheing: true

      - run:
          name: Install Docker Compose
          shell: /bin/bash
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.25.3/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
            echo 'export PATH=$PATH:/usr/local/bin/' >> $BASH_ENV
            echo $PATH
            docker-compose build
            docker-compose up
