local:
    server:
        address: ":9999"
    mysql:
        address: "docker.for.mac.localhost:3306"
        databaseName: "practice"
        username: "asymptoter"
        password: "password"
    redis:
        address: "127.0.0.1:6379"
